# Generated by Django 3.1.5 on 2021-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_feedback_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
