# Generated by Django 3.1.5 on 2021-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210329_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
